id: PB834A3AA
initial_creation_type: ocr
source_metadata:
  volumes:
    db0074c55c474a9bb814f0d543b2b394:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: རིན་པོ་ཆེ་སྒྲོན་མ།
      total_pages: 1902
      volume_number: 26
