id: D94D97878
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:47:06+00:00'
last_modified: '2022-05-26T11:12:52.892303+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    6d63:
      image_group_id: I1PD95871
      title: རིན་པོ་ཆེ་སྒྲོན་མ།
      total_pages: 1902
      order: 26
      base_file: 6d63.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
